on:
  push:
    branches:
      - main
      - v**

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          default-branch: ${{ github.ref_name }}

#        if: github.ref_name == 'main'

#      - uses: google-github-actions/release-please-action@v3
#        with:
#          command: manifest
#          default-branch: ${{ github.ref_name }}
#        if: startsWith(github.ref, 'refs/heads/v')